### ISSUE TITLE
Rbac not enough rights

### ISSUE THREAD

**Issue by attiolli** [joshuakraitberg/cert-manager-webhook-duckdns#3] opened 2022-10-31 07:24 UTC
@joshuakraitberg : I am having problems with your repo regarding rbac. The rbac does not seem to define the sufficient rights. I am using v1.24.6+k3s1" and cert-manager v1.10.0. 

The error is shown in challenge events when the cert order is stuck on pending state:
"Warning PresentError 22m (x28 over 10h) cert-manager-challenges Error presenting challenge: duckdns.mydomain.duckdns.org is forbidden: User "system:serviceaccount:cert-manager:cert-manager" cannot create resource "duckdns" in API group "mydomain.duckdns.org" at the cluster scope"

**Comment by joshuakraitberg** [comment] 2022-10-31 16:02
That error is caused by cert-manager's service account not the one created in this chart.  I was able to successfully upgrade to v1.10.0. 

What do your values files for cert-manager and this chart look like?

**Comment by attiolli** [comment] 2022-11-01 05:39
Hi,

Thanks for verifying with cert-manager v.1.10.0.

These are my configs:

`# My cert-manager:`
https://github.com/attiolli/k3s-cluster-dev/blob/main/cluster/core/cert-manager/helm-release.yaml

`# My duckdns:`
https://github.com/attiolli/k3s-cluster-dev/blob/main/cluster/core/cert-manager-duckdns/helm-release.yaml

**Comment by joshuakraitberg** [comment] 2022-11-01 21:16
You've set `installCRDs: false` https://github.com/attiolli/k3s-cluster-dev/blob/d3dcff5fdf071e3839e54ecdab21ddb2f1624361/cluster/core/cert-manager/helm-release.yaml#L19, without installing the CRDs elsewhere.  

I use "https://github.com/cert-manager/cert-manager/releases/download/v1.10.0/cert-manager.crds.yaml" to install from a kustomization.

**Comment by attiolli** [comment] 2022-11-02 10:23
I actually remember I installed the crds after the cert-manager setup and now based on  running this command I assume crds are installed:

```
$ kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.10.0/cert-manager.crds.yaml
customresourcedefinition.apiextensions.k8s.io/clusterissuers.cert-manager.io unchanged
customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io unchanged
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io unchanged
customresourcedefinition.apiextensions.k8s.io/issuers.cert-manager.io unchanged
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io unchanged
customresourcedefinition.apiextensions.k8s.io/orders.acme.cert-manager.io unchanged
```

But still getting:

```
 Warning  PresentError  4m23s (x8 over 14m)     cert-manager-challenges  Error presenting challenge: duckdns.xxx.duckdns.org is forbidden: User
"system:serviceaccount:cert-manager:cert-manager" cannot create resource "duckdns" in API group "xxx.duckdns.org" at the cluster scope
```

**Comment by joshuakraitberg** [comment] 2022-11-02 17:12
You can try adding this to your release.yaml for cert-manager-webhook-duckdns:
```
spec:
  dependsOn:
    - name: cert-manager
```

You are also missing Value.groupName.  It should be required but is missing from README.

**Comment by attiolli** [comment] 2022-11-06 18:47
Added the dependsOn and Value.groupName as seen in the repo now, but still getting the error:

Warning  PresentError  2d7h (x56 over 3d7h)  cert-manager-challenges  Error presenting challenge: duckdns.xxx.duckdns.org is forbidden: User "system:serviceaccount:cert-manager:cert-manager" cannot create resource "duckdns" in API group "xxx.duckdns.org" at the cluster scope

Do i need to re-deploy the duckdns webhook or how should I try to fix the issue?

**Comment by d-uzlov** [comment] 2023-05-14 08:41
I also had this issue.
For me it was caused by wrong namespaces.

The helm chart of this webhook is constructed to be deployed into `cert-manager` namespace (namespace where cert-manager deployment, service account, secrets live).

My mistake was that I didn't set the namespace via the helm command, and tried to set it using Kustomize.
Kustomize broke `authentication-reader` RoleBinding for me, and it also broke `domain-solver` ClusterRoleBinding.

Broken `authentication-reader` RoleBinding causes a different error (the webhook doesn't start without it).
Broken `domain-solver` ClusterRoleBinding causes `cannot create resource "duckdns"` in cert-manager logs, just like in the original post of this issue.

I didn't check it, but I think that if you try to deploy the webhook in a separate namespace, then `authentication-reader` RoleBinding will be fine, but `domain-solver` ClusterRoleBinding will still be broken.
The solution should be to manually edit `domain-solver` ClusterRoleBinding to point to correct namespace:
https://github.com/joshuakraitberg/cert-manager-webhook-duckdns/blob/b9af81924d42d12f3bf88b83993412e61222df89/charts/cert-manager-webhook-duckdns/templates/rbac.yaml#L76
Or simply deploy the webhook into cert-manager namespace.

And maybe it would be a good idea to add a separate configurable value for helm to point ClusterRoleBinding to a separate namespace, for cases when webhook doesn't share namespace with cert-manager.

**Comment by joshuakraitberg** [comment] 2023-07-19 17:45
@d-uzlov Thanks for the analysis.  

The webhook should be in the same namespace.  I'll close this.

**Closed as completed by joshuakraitberg** 2023-07-19 17:45 UTC
